name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Read a variable
        run: echo "My app id value is ${{ vars.DOCKER_USERNAME }}"
      - name: Tell me the secret
        run: echo "My secret value is ${{ secrets.DOCKERHUB_TOKEN }}"
