name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "DOCKER_USERNAME: $DOCKER_USERNAME"
          echo "DOCKERHUB_TOKEN set: $([[ -n "$DOCKERHUB_TOKEN" ]] && echo true || echo false)"
