name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Read a variable
        run: echo "My app id value is ${{ vars.DOCKER_USERNAME }}"
      - name: Tell me the secret
        run: echo "My secret value is ${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
